TeamCrops/good-crop

src/main/java/com/crop/goodcrop/domain/member/controller/MemberController.java, src/main/java/com/crop/goodcrop/domain/member/dto/request/MemberRequestDto.java, src/main/java/com/crop/goodcrop/domain/member/dto/response/MemberResponseDto.java, src/main/java/com/crop/goodcrop/domain/member/service/MemberService.java
- 유저
- 프로필 조회 관련 dto, service, controller 작성
- 프로필 수정, 멤버 탈퇴
- #7
=> feat : 프로필 조회 #7

src/main/java/com/crop/goodcrop/domain/like/controller/LikeController.java, src/main/java/com/crop/goodcrop/domain/like/service/LikeService.java
- 좋아요 취소 담당 파트
- 좋아요 취소 기능 구현
- 미정
- #14
=> feat: 좋아요 취소 #14

src/main/java/com/crop/goodcrop/domain/member/controller/MemberController.java, src/main/java/com/crop/goodcrop/domain/member/dto/request/MemberUpdateRequestDto.java, src/main/java/com/crop/goodcrop/domain/member/dto/response/MemberUpdateResponseDto.java, src/main/java/com/crop/goodcrop/domain/member/entity/Member.java, src/main/java/com/crop/goodcrop/domain/member/service/MemberService.java
- 프로필 수정
- 프로필 수정 dto, 서비스, 컨트롤러 
- 유저 탈퇴
- #12
=> feat : 프로필 수정 #12

build.gradle, src/main/java/com/crop/goodcrop/domain/review/controller/ReviewController.java, src/main/java/com/crop/goodcrop/domain/review/dto/request/ReviewRequestDto.java, src/main/java/com/crop/goodcrop/domain/review/dto/response/ReviewResponseDto.java, src/main/java/com/crop/goodcrop/domain/review/entity/Review.java, src/main/java/com/crop/goodcrop/domain/review/service/ReviewService.java, src/test/java/com/crop/goodcrop/review/ReviewServiceTest.java
- 리뷰 등록
- 리뷰 등록 API 추가
- 리뷰 등록 테스트 코드 추가
- 리뷰 보기/수정/삭제 구현
- #6
=> feat(review-create): 리뷰 등록

src/main/java/com/crop/goodcrop/domain/auth/dto/request/SignInRequestDto.java, src/main/java/com/crop/goodcrop/domain/member/repository/MemberRepository.java, src/main/java/com/crop/goodcrop/exception/ErrorCode.java, src/main/java/com/crop/goodcrop/security/config/WebSecurityConfig.java, src/main/java/com/crop/goodcrop/security/entity/UserDetailsImpl.java, src/main/java/com/crop/goodcrop/security/filter/AuthFilter.java, src/main/java/com/crop/goodcrop/security/filter/JwtAuthenticationFilter.java, src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java, src/main/java/com/crop/goodcrop/security/service/UserDetailsServiceImpl.java, src/main/java/com/crop/goodcrop/security/util/JwtUtil.java
- Spring security
- Jwt 
- 로그인
- Spring security 
- Jwt 토큰 생성 및 유효성 검사
- 인증/인가 필터
- Filter에서 로그인 처리
-  사용자 인증  UserDetailsImpl 및 UserDetailsServiceImpl 
- #9
=> feat: security,jwt,로그인 #9

src/main/java/com/crop/goodcrop/domain/auth/service/AuthService.java
- 회원가입
- 회원가입 Transactional 어노테이션 추가
- #22
=> feat: Transactional 어노테이션 추가 #22

src/main/java/com/crop/goodcrop/domain/like/dto/request/LikeRequestDto.java, src/test/java/com/crop/goodcrop/like/LikeControllerTest.java, src/test/java/com/crop/goodcrop/like/LikeServiceTest.java, src/test/java/com/crop/goodcrop/like/LikeTest.java
- 좋아요 테스트 코드 작성
- 좋아요 테스트 코드 작성
- dummy data 적재
- #14, #5
=> feat: 좋아요 테스트 코드 작성

src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java
- security
-  JwtAuthorizationFilter createAuthentication메소드 UsernamePasswordAuthenticationToken null 추가
-  commit메세지에서 setAuthentication ->createAuthentication 입니다.  잘 못 작성되었습니다. 참고 바랍니다.
- #30
=> feat:  JwtAuthorizationFilter  변경 사항#30

src/main/java/com/crop/goodcrop/domain/member/controller/MemberController.java, src/main/java/com/crop/goodcrop/domain/member/dto/request/MemberDeleteRequestDto.java, src/main/java/com/crop/goodcrop/domain/member/service/MemberService.java, src/main/java/com/crop/goodcrop/exception/ErrorCode.java, src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java
- 회원 탈퇴
- 회원의 아이디, 패스워드를 입력 받아 회원 탈퇴
- 에러 코드 추가
- 시큐리티 적용
- 나머지 멤버 도메인에 시큐리티 적용
- 테스트 코드 작성
- #24
=> feat : 회원탈퇴

src/main/java/com/crop/goodcrop/domain/like/controller/LikeController.java, src/main/java/com/crop/goodcrop/domain/like/service/LikeService.java, src/test/java/com/crop/goodcrop/like/LikeControllerTest.java, src/test/java/com/crop/goodcrop/like/LikeServiceTest.java
- 좋아요 테스트 코드 작성
- 좋아요 테스트 코드 작성
- dummy data 적재
- #14, #5
=> fix: 좋아요 security 적용 및 테스트 코드 작성 #14, #5

src/main/java/com/crop/goodcrop/domain/member/controller/MemberController.java, src/main/java/com/crop/goodcrop/domain/member/service/MemberService.java
- 프로필 조회 시큐리티 적용
- 로그인 후 기능 사용 가능
- 프로필 수정 시큐리티 적용
- #7
=> 프로필 조회 시큐리티 적용

src/main/java/com/crop/goodcrop/domain/member/controller/MemberController.java, src/main/java/com/crop/goodcrop/domain/member/service/MemberService.java
- 🔘 담당 파트
- 프로필 수정
- 🔎 작업 상세 내용
- 프로필 수정 시큐리티 적용
- 🔧 앞으로의 과제
- 유저 도메인 테스트 코드 작성
- ➕ 이슈 링크
- #12
=> 프로필 수정 시큐리티 적용 

src/main/java/com/crop/goodcrop/domain/auth/dto/request/SignUpRequestDto.java, src/test/java/com/crop/goodcrop/auth/SignupServiceTest.java
=> feat: 회원가입 테스트코드 작성 #35

src/test/java/com/crop/goodcrop/member/MemberServiceTest.java
- 프로필 조회 테스트
- 프로필 조회 성공 테스트
- id 불일치 실패 테스트
- 존재하지 않는 사용자 조회 실패 패스트
- 프로필 수정 테스트
- 회원 탈퇴 테스트
- #7
=> 프로필 조회 테스트

src/test/java/com/crop/goodcrop/member/MemberDeleteServiceTest.java, src/test/java/com/crop/goodcrop/member/MemberRetrieveServiceTest.java, src/test/java/com/crop/goodcrop/member/MemberServiceTest.java, src/test/java/com/crop/goodcrop/member/MemberUpdateServiceTest.java
- 유저 도메인 테스트
<br>
1. 프로필 조회 관련 테스트
2. 프로필 수정 관련 테스트
3. 회원탈퇴 테스트
<br>
<br>
- #47
=> 유저 도메인 테스트 

src/main/java/com/crop/goodcrop/domain/review/controller/ReviewController.java, src/main/java/com/crop/goodcrop/domain/review/service/ReviewService.java, src/main/java/com/crop/goodcrop/exception/ErrorCode.java, src/test/java/com/crop/goodcrop/review/ReviewServiceTest.java
- 리뷰 삭제 API
<br>
1. 리뷰 삭제 API
2. 리뷰 삭제 테스트 코드
<br>
- Security 적용
- 불필요한 코드 정리
<br>
- #50
=>  feat: 리뷰 삭제

src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java
- sequrity
- JwtAuthorizationFilter createAuthentication 
null 대신 userDetails.getAuthorities()로 권한 정보 설정
- #42
=> feat: JwtAuthorizationFilter #42

src/main/java/com/crop/goodcrop/domain/member/service/MemberService.java, src/main/java/com/crop/goodcrop/exception/ErrorCode.java, src/test/java/com/crop/goodcrop/member/MemberUpdateServiceTest.java
유저 도메인
다른 아이디로 작업 수행할 때 권한없음 예외처리가 나도록 한다.
인기검색어 테이블
=> fix(member-service) : 예외처리 수정 

build.gradle, src/main/java/com/crop/goodcrop/cacheFile/CacheConfig.java, src/main/java/com/crop/goodcrop/cacheFile/redisConfig.java, src/main/java/com/crop/goodcrop/domain/product/controller/ProductController.java, src/main/java/com/crop/goodcrop/domain/product/service/ProductService.java, src/main/java/com/crop/goodcrop/domain/trend/repository/TopKeywordRepository.java, src/main/java/com/crop/goodcrop/security/config/WebSecurityConfig.java, src/test/java/com/crop/goodcrop/domain/product/service/ProductCacheTest.java
- 상품검색 V2 
- 상품검색 V2 Redis 캐시 적용
- #64
=> feat: 상품검색 V2 Redis 캐시 적용 #64

src/main/java/com/crop/goodcrop/config/RedisConfig.java, src/main/java/com/crop/goodcrop/domain/trend/controller/TopKeywordController.java, src/main/java/com/crop/goodcrop/domain/trend/dto/TopKeywordCacheDto.java, src/main/java/com/crop/goodcrop/domain/trend/service/TopKeywordService.java
- 인기 검색어 version2
- top키워드가 캐싱처리되지 않는 현상 수정
- 테스트 및 버그수정
- #54
=> fix: 버그 수정 #54
